import { Schema, type InferSchemaType } from 'mongoose';

import { modelFrom } from '@/lib/model';
import { roundMoney } from '@/lib/money';
import {
  INCOME_CATEGORIES,
  OUTCOME_CATEGORIES,
  PAYMENT_METHODS,
  TRANSACTION_TYPES,
} from '@/types/constants';

/**
 * Income and expense ledger.
 *
 * Named `FinancialTransaction` rather than `Transaction` to avoid any
 * confusion with MongoDB session transactions, which this app also uses for
 * atomic checkout. The UI still labels this "Transactions".
 *
 * POS sales write their income row here automatically; operational costs are
 * entered by hand.
 */
const financialTransactionSchema = new Schema(
  {
    type: {
      type: String,
      required: true,
      enum: {
        values: TRANSACTION_TYPES,
        message: '{VALUE} is not a valid transaction type',
      },
    },

    amount: {
      type: Number,
      required: [true, 'Amount is required'],
      // Zero is allowed, not negative. A POS sale that is comped out by a 100%
      // discount is still a real transaction — stock left the shelf — but no
      // money changed hands, so its ledger row is legitimately 0. Hand-entered
      // entries cannot exploit this: createTransactionSchema requires a positive
      // amount, so this looser floor is reachable only from checkout.
      min: [0, 'Amount cannot be negative'],
      set: (value: number) => roundMoney(value),
    },

    category: {
      type: String,
      required: [true, 'Category is required'],
      enum: {
        values: [...INCOME_CATEGORIES, ...OUTCOME_CATEGORIES],
        message: '{VALUE} is not a valid transaction category',
      },
    },

    paymentMethod: {
      type: String,
      required: [true, 'Payment method is required'],
      enum: {
        values: PAYMENT_METHODS,
        message: '{VALUE} is not a valid payment method',
      },
    },

    referenceNote: { type: String, trim: true, maxlength: 300 },

    /**
     * Business date, separate from the Mongo insert timestamp. A sale rung up
     * after midnight still belongs to the day the customer shopped, and daily
     * reports group on this field.
     */
    occurredAt: { type: Date, default: () => new Date() },

    /** Present only on rows generated by the POS. */
    sale: { type: Schema.Types.ObjectId, ref: 'Sale' },
    productBreakdown: {
      type: [
        new Schema(
          {
            product: { type: Schema.Types.ObjectId, ref: 'Product' },
            name: { type: String, required: true },
            quantity: { type: Number, required: true },
            unitPrice: {
              type: Number,
              required: true,
              set: (value: number) => roundMoney(value),
            },
            lineTotal: {
              type: Number,
              required: true,
              set: (value: number) => roundMoney(value),
            },
          },
          { _id: false },
        ),
      ],
      default: undefined,
    },
  },
  {
    timestamps: true,
    toJSON: { virtuals: true },
    toObject: { virtuals: true },

    /**
     * Cross-field guard, as a *schema-level* validator because it spans two
     * fields. "Sales" is an income category and the operating-cost categories are
     * outcome categories; without this a sale could be filed as an expense and
     * quietly distort the profit figures.
     *
     * Note this must live in the schema options, not among the field definitions —
     * inside them Mongoose reads `validate` as a path named "validate".
     */
    validate: {
      validator: (doc: { type?: string; category?: string }) =>
        doc.type === 'income'
          ? (INCOME_CATEGORIES as readonly string[]).includes(doc.category ?? '')
          : (OUTCOME_CATEGORIES as readonly string[]).includes(doc.category ?? ''),
      message: (props: { path?: string; value?: unknown }) =>
        props.path === 'category' && props.value === 'Sales'
          ? 'Sales is an income category and cannot be recorded as an outcome.'
          : 'This category is an operating cost and cannot be recorded as income.',
    },
  },
);

financialTransactionSchema.index({ occurredAt: -1 });
financialTransactionSchema.index({ type: 1, occurredAt: -1 });
financialTransactionSchema.index({ category: 1, occurredAt: -1 });

/** Income minus expense, positive when the shop is in profit. */
financialTransactionSchema.virtual('signedAmount').get(function (this: {
  type?: string;
  amount?: number;
}) {
  const amount = this.amount ?? 0;
  return this.type === 'income' ? amount : -amount;
});

export type FinancialTransactionShape = InferSchemaType<
  typeof financialTransactionSchema
>;

export const FinancialTransaction = modelFrom<FinancialTransactionShape>(
  'FinancialTransaction',
  financialTransactionSchema,
);